service: amirotate
provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
  - Effect: Allow
    Action:
    - ec2:CreateImage
    - ec2:CreateTags
    - ec2:DeleteSnapshot
    - ec2:DeregisterImage
    - ec2:DescribeImages
    - ec2:DescribeInstances
    - ec2:DescribeSnapshots
    - ec2:DescribeTags
    Resource: "*"
plugins:
- serverless-webpack
functions:
  create:
    handler: create.default
  delete:
    handler: delete.default
